In [1]:
!pip install scikit-learn==1.3.0


  Obtaining dependency information for scikit-learn==1.3.0 from https://files.pythonhosted.org/packages/77/85/bff3a1e818ec6aa3dd466ff4f4b0a727db9fdb41f2e849747ad902ddbe95/scikit_learn-1.3.0-cp311-cp311-win_amd64.whl.metadata
   ---------------------------------------- 0.0/9.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.2 MB 495.5 kB/s eta 0:00:19
    --------------------------------------- 0.2/9.2 MB 1.8 MB/s eta 0:00:06
   -- ------------------------------------- 0.5/9.2 MB 3.2 MB/s eta 0:00:03
   --- ------------------------------------ 0.9/9.2 MB 4.2 MB/s eta 0:00:02
   ----- ---------------------------------- 1.3/9.2 MB 5.2 MB/s eta 0:00:02
   ------- -------------------------------- 1.8/9.2 MB 5.9 MB/s eta 0:00:02
   --------- ------------------------------ 2.3/9.2 MB 6.5 MB/s eta 0:00:02
   ------------ --------------------------- 2.8/9.2 MB 7.1 MB/s eta 0:00:01
   -------------- ---------

DEPRECATION: Loading egg at c:\users\tanuj\anaconda3\lib\site-packages\apache_beam-2.56.0-py3.11-win-amd64.egg is deprecated. pip 23.3 will enforce this behaviour change. A possible replacement is to use pip for package installation..
DEPRECATION: Loading egg at c:\users\tanuj\anaconda3\lib\site-packages\avro_python3-1.10.2-py3.11.egg is deprecated. pip 23.3 will enforce this behaviour change. A possible replacement is to use pip for package installation..
DEPRECATION: Loading egg at c:\users\tanuj\anaconda3\lib\site-packages\contextlib2-21.6.0-py3.11.egg is deprecated. pip 23.3 will enforce this behaviour change. A possible replacement is to use pip for package installation..
DEPRECATION: Loading egg at c:\users\tanuj\anaconda3\lib\site-packages\cython-3.0.10-py3.11.egg is deprecated. pip 23.3 will enforce this behaviour change. A possible replacement is to use pip for package installation..
DEPRECATION: Loading egg at c:\users\tanuj\anaconda3\lib\site-packages\lvis-0.5.3-py3.11.egg i

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df = pd.read_csv("C:/Users/tanuj/Downloads/predictive_maintenance (1).csv")

In [3]:
df.head()

UDI Product ID Type  Air temperature [K]  Process temperature [K]   
0    1     M14860    M                298.1                    308.6  \
1    2     L47181    L                298.2                    308.7   
2    3     L47182    L                298.1                    308.5   
3    4     L47183    L                298.2                    308.6   
4    5     L47184    L                298.2                    308.7   

   Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  Target Failure Type  
0                    1551         42.8                0       0   No Failure  
1                    1408         46.3                3       0   No Failure  
2                    1498         49.4                5       0   No Failure  
3                    1433         39.5                7       0   No Failure  
4                    1408         40.0                9       0   No Failure

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   UDI                      10000 non-null  int64  
 1   Product ID               10000 non-null  object 
 2   Type                     10000 non-null  object 
 3   Air temperature [K]      10000 non-null  float64
 4   Process temperature [K]  10000 non-null  float64
 5   Rotational speed [rpm]   10000 non-null  int64  
 6   Torque [Nm]              10000 non-null  float64
 7   Tool wear [min]          10000 non-null  int64  
 8   Target                   10000 non-null  int64  
 9   Failure Type             10000 non-null  object 
dtypes: float64(3), int64(4), object(3)
memory usage: 781.4+ KB


In [5]:
df['Type'].nunique()

3

In [6]:
df.isnull().sum()

UDI                        0
Product ID                 0
Type                       0
Air temperature [K]        0
Process temperature [K]    0
Rotational speed [rpm]     0
Torque [Nm]                0
Tool wear [min]            0
Target                     0
Failure Type               0
dtype: int64

In [7]:
df.shape

(10000, 10)

In [8]:
df['Failure Type'].value_counts()

Failure Type
No Failure                  9652
Heat Dissipation Failure     112
Power Failure                 95
Overstrain Failure            78
Tool Wear Failure             45
Random Failures               18
Name: count, dtype: int64

Dataset is imbalanced

In [9]:
df[df['Target']==1]

UDI Product ID Type  Air temperature [K]  Process temperature [K]   
50      51     L47230    L                298.9                    309.1  \
69      70     L47249    L                298.9                    309.0   
77      78     L47257    L                298.8                    308.9   
160    161     L47340    L                298.4                    308.2   
161    162     L47341    L                298.3                    308.1   
...    ...        ...  ...                  ...                      ...   
9758  9759     L56938    L                298.6                    309.8   
9764  9765     L56944    L                298.5                    309.5   
9822  9823     L57002    L                298.5                    309.4   
9830  9831     L57010    L                298.3                    309.3   
9974  9975     L57154    L                298.6                    308.2   

      Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  Target   
50                      2861          4.6              143       1  \
69                      1410         65.7              191       1   
77                      1455         41.3              208       1   
160                     1282         60.7              216       1   
161                     1412         52.3              218       1   
...                      ...          ...              ...     ...   
9758                    2271         16.2              218       1   
9764                    1294         66.7               12       1   
9822                    1360         60.9              187       1   
9830                    1337         56.1              206       1   
9974                    1361         68.2              172       1   

            Failure Type  
50         Power Failure  
69         Power Failure  
77     Tool Wear Failure  
160   Overstrain Failure  
161   Overstrain Failure  
...                  ...  
9758   Tool Wear Failure  
9764       Power Failure  
9822  Overstrain Failure  
9830  Overstrain Failure  
9974       Power Failure  

[339 rows x 10 columns]

# Train test split

In [10]:
X = df.iloc[:,2:8]
y = df.iloc[:,-1]

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 42)
y_train.shape

(8000,)

# Ordinal Encoding

In [11]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=[['L', 'M', 'H']])
oe.fit(X_train[['Type']])
X_train['Type'] = oe.transform(X_train[['Type']]).astype(int)
X_test['Type'] = oe.transform(X_test[['Type']]).astype(int)

In [12]:
X_train.head()

Type  Air temperature [K]  Process temperature [K]   
9254     0                298.3                    309.1  \
1561     0                298.2                    308.4   
1670     0                298.2                    307.8   
6087     1                300.9                    310.8   
6669     0                301.4                    310.5   

      Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  
9254                    1616         31.1              195  
1561                    1388         53.8              137  
1670                    1528         31.1              194  
6087                    1599         33.0                7  
6669                    1571         33.9              208

# Label encoding

In [13]:
from sklearn.preprocessing import LabelEncoder
categories = ['No Failure', 'Heat Dissipation Failure', 'Power Failure', 'Overstrain Failure', 'Tool Wear Failure', 'Random Failures']
custom_encoder = {cat: i for i, cat in enumerate(categories)}
y_train_encoded = [custom_encoder.get(cat, len(categories)) for cat in y_train]
y_test_encoded = [custom_encoder.get(cat, len(categories)) for cat in y_test]
le = LabelEncoder()
le.fit(list(custom_encoder.values()))
y_train = le.transform(y_train_encoded)
y_test = le.transform(y_test_encoded)



# Logistic Regression 

In [14]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

clf = LogisticRegression(solver='lbfgs', max_iter=10000, class_weight='balanced')

clf.fit(X_train, y_train)

# Predict the labels of the test set
y_pred = clf.predict(X_test)

log_train = round(clf.score(X_train, y_train) * 100, 2)
log_accuracy = round(accuracy_score(y_pred, y_test) * 100, 2)


print("Training Accuracy    :",log_train ,"%")
print("Model Accuracy Score :",log_accuracy ,"%")
print("\033[1m--------------------------------------------------------\033[0m")
print("Classification_Report: \n",classification_report(y_test,y_pred))
print("\033[1m--------------------------------------------------------\033[0m")
print(confusion_matrix(y_test,y_pred))

Training Accuracy    : 61.56 %
Model Accuracy Score : 61.25 %
--------------------------------------------------------
Classification_Report: 
               precision    recall  f1-score   support

           0       1.00      0.60      0.75      1935
           1       0.20      1.00      0.33        15
           2       0.42      0.90      0.57        20
           3       0.28      0.92      0.43        13
           4       0.06      0.91      0.11        11
           5       0.00      0.00      0.00         6

    accuracy                           0.61      2000
   macro avg       0.32      0.72      0.37      2000
weighted avg       0.97      0.61      0.74      2000

--------------------------------------------------------
[[1170   59   25   30  162  489]
 [   0   15    0    0    0    0]
 [   0    2   18    0    0    0]
 [   0    0    0   12    1    0]
 [   0    0    0    1   10    0]
 [   5    0    0    0    1    0]]


C:\Users\tanuj\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


The hyperparameter tuning has significantly improved the performance of your Logistic Regression model on the training and test sets, especially for the majority class. However, there are still challenges with the minority classes, particularly Class 4 (Tool Wear Failure) and Class 5 (Random Failures).

# Decision Tree

In [16]:
# Decision Tree
from sklearn.tree import DecisionTreeClassifier
decision = DecisionTreeClassifier()
decision.fit(X_train, y_train)
y_pred_dec = decision.predict(X_test)

decision_train = round(decision.score(X_train, y_train) * 100, 2)
decision_accuracy = round(accuracy_score(y_pred_dec, y_test) * 100, 2)

print("Training Accuracy    :",decision_train ,"%")
print("Model Accuracy Score :",decision_accuracy ,"%")
print("\033[1m--------------------------------------------------------\033[0m")
print("Classification_Report: \n",classification_report(y_test,y_pred_dec))
print("\033[1m--------------------------------------------------------\033[0m")


Training Accuracy    : 100.0 %
Model Accuracy Score : 97.45 %
--------------------------------------------------------
Classification_Report: 
               precision    recall  f1-score   support

           0       0.99      0.99      0.99      1935
           1       0.87      0.87      0.87        15
           2       0.71      0.85      0.77        20
           3       0.50      0.62      0.55        13
           4       0.11      0.09      0.10        11
           5       0.00      0.00      0.00         6

    accuracy                           0.97      2000
   macro avg       0.53      0.57      0.55      2000
weighted avg       0.97      0.97      0.97      2000

--------------------------------------------------------


In [17]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, classification_report

# Define the parameter grid for hyperparameter tuning
param_grid = {
    'max_depth': [None, 10, 20, 30, 40],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 5],
    
}

# Initialize the Decision Tree model
decision = DecisionTreeClassifier(random_state=42,class_weight='balanced')

# Set up GridSearchCV for hyperparameter tuning
grid_search = GridSearchCV(estimator=decision, param_grid=param_grid, 
                           scoring='accuracy', cv=5, n_jobs=-1, verbose=2)

# Fit the model on training data
grid_search.fit(X_train, y_train)

# Get the best parameters and model
best_params = grid_search.best_params_
best_decision = grid_search.best_estimator_

# Predict on the test set
y_pred_dec = best_decision.predict(X_test)

# Calculate accuracy and classification report
decision_train = round(best_decision.score(X_train, y_train) * 100, 2)
decision_accuracy = round(accuracy_score(y_pred_dec, y_test) * 100, 2)

print("Best Parameters:", best_params)
print("\033[1m--------------------------------------------------------\033[0m")
print("Training Accuracy    :", decision_train, "%")
print("Model Accuracy Score :", decision_accuracy, "%")
print("\033[1m--------------------------------------------------------\033[0m")
print("Classification_Report: \n", classification_report(y_test, y_pred_dec))
print("\033[1m--------------------------------------------------------\033[0m")


Fitting 5 folds for each of 45 candidates, totalling 225 fits
Best Parameters: {'max_depth': 30, 'min_samples_leaf': 1, 'min_samples_split': 2}
--------------------------------------------------------
Training Accuracy    : 100.0 %
Model Accuracy Score : 97.25 %
--------------------------------------------------------
Classification_Report: 
               precision    recall  f1-score   support

           0       0.99      0.99      0.99      1935
           1       0.65      0.73      0.69        15
           2       0.73      0.55      0.63        20
           3       0.47      0.69      0.56        13
           4       0.25      0.18      0.21        11
           5       0.00      0.00      0.00         6

    accuracy                           0.97      2000
   macro avg       0.52      0.52      0.51      2000
weighted avg       0.97      0.97      0.97      2000

--------------------------------------------------------


Overfitting

# Random Forest

In [20]:
# Random Forest
from sklearn.ensemble import RandomForestClassifier
random_forest = RandomForestClassifier(n_estimators=100)
random_forest.fit(X_train, y_train)
y_pred_rf = random_forest.predict(X_test)
random_forest.score(X_train, y_train)

random_forest_train = round(random_forest.score(X_train, y_train) * 100, 2)
random_forest_accuracy = round(accuracy_score(y_pred_rf, y_test) * 100, 2)

print("Training Accuracy    :",random_forest_train ,"%")
print("Model Accuracy Score :",random_forest_accuracy ,"%")
print("\033[1m--------------------------------------------------------\033[0m")
print("Classification_Report: \n",classification_report(y_test,y_pred_rf))
print("\033[1m--------------------------------------------------------\033[0m")

Training Accuracy    : 100.0 %
Model Accuracy Score : 98.2 %
--------------------------------------------------------
Classification_Report: 
               precision    recall  f1-score   support

           0       0.98      1.00      0.99      1935
           1       0.92      0.73      0.81        15
           2       0.79      0.75      0.77        20
           3       0.89      0.62      0.73        13
           4       0.00      0.00      0.00        11
           5       0.00      0.00      0.00         6

    accuracy                           0.98      2000
   macro avg       0.60      0.52      0.55      2000
weighted avg       0.97      0.98      0.98      2000

--------------------------------------------------------


C:\Users\tanuj\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\tanuj\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\tanuj\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [26]:
cm = confusion_matrix(y_test, y_pred_rf)

print(cm)

[[1928    2    4    1    0    0]
 [   3   12    0    0    0    0]
 [   5    0   15    0    0    0]
 [   5    0    1    7    0    0]
 [  10    0    0    1    0    0]
 [   6    0    0    0    0    0]]


# SVM

In [18]:
# Support Vector Machines
from sklearn.svm import SVC
svc = SVC()
svc.fit(X_train, y_train)
y_pred_svc = svc.predict(X_test)

svc_train = round(svc.score(X_train, y_train) * 100, 2)
svc_accuracy = round(accuracy_score(y_pred_svc, y_test) * 100, 2)

print("Training Accuracy    :",svc_train ,"%")
print("Model Accuracy Score :",svc_accuracy ,"%")
print("\033[1m--------------------------------------------------------\033[0m")
print("Classification_Report: \n",classification_report(y_test,y_pred_svc))
print("\033[1m--------------------------------------------------------\033[0m")

Training Accuracy    : 96.58 %
Model Accuracy Score : 96.85 %
--------------------------------------------------------
Classification_Report: 
               precision    recall  f1-score   support

           0       0.97      1.00      0.98      1935
           1       0.00      0.00      0.00        15
           2       0.75      0.15      0.25        20
           3       0.00      0.00      0.00        13
           4       0.00      0.00      0.00        11
           5       0.00      0.00      0.00         6

    accuracy                           0.97      2000
   macro avg       0.29      0.19      0.21      2000
weighted avg       0.94      0.97      0.95      2000

--------------------------------------------------------


C:\Users\tanuj\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\tanuj\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\tanuj\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [41]:
import pickle
pickle.dump(random_forest,open('model.pkl','wb'))


In [42]:
columns = df.columns.tolist()
columns

['UDI',
 'Product ID',
 'Type',
 'Air temperature [K]',
 'Process temperature [K]',
 'Rotational speed [rpm]',
 'Torque [Nm]',
 'Tool wear [min]',
 'Target',
 'Failure Type']

In [32]:
!pip install streamlit -q


In [38]:
!wget -q -O - ipv4.icanhazip.com

35.222.194.34


In [ ]:
! streamlit run app.py & npx localtunnel --port 8501




  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.28.0.12:8501
  External URL: http://35.222.194.34:8501

npx: installed 22 in 2.32s
your url is: https://major-ducks-tie.loca.lt
